[package]
name = "ksearch"
version = "2.0.3"
edition = "2021"

[dependencies]
clap = { version = "4.2.5", features = ["cargo"] }
toml = "0.8.10"
serde = { version = "1.0.160", features = ["derive"] }

[build-dependencies]
clap = { version = "4.2.5", features = ["cargo"] }
clap_complete = "4.2.1"
